### ISSUE TITLE
Ask for environment variables

### ISSUE THREAD

**Issue by vdo** [dappnode/DAppNodeSDK#10]
The (optional) environment variables settings are missing in the `init` wizard. Would be nice to ask for them, comma separated, like in the ports section.

**Comment by dapplion** [comment]
I don't think that asking for ENVs and ports in the `init` command is the best approach. You are not typically sure of those settings until you start the DNP development. Maybe a better approach would be to have a sort of manifest editor wizard to edit the manifest during development, instead than on init. @vdo what do you think?

**Comment by dapplion** [comment]
Closing since this is not a priority in the foreseeable future
