### ISSUE TITLE
Docker save should check if image is already created

### ISSUE THREAD

**Issue by vdo** [dappnode/DAppNodeSDK#12]
When doing the `docker save` command, we should check if it's present and avoid overwrite it.

**Comment by wildmolasses** [comment]
Hi, I would like to work on this. Is it ok to use `fs.accessSync()` to check existence of file, then prompt for overwrite via notify npm module (used elsewhere in project)? If so I will file a PR.

**Comment by dapplion** [comment]
Thank you so much for your contribution! Out of your PR I extended the concept to automatically verify if the compressed image file should be re-done or not by keeping a mapped cache of the files' hashes.
49e2ce6
