### ISSUE TITLE
build command succeeds despite consistency errors in config files

### ISSUE THREAD

**Issue by sponnet** [dappnode/DAppNodeSDK#13]
The `build` command should verify consistency of the config files and stop if there are errors, or at least report these errors.

More specifically check that the `name` and `version` fields in the `dappnode_package.json` match 
with the `docker-compose.yml` service name and image name. 

dappnode_package.json
```
{ name: '<name>',
  version: '<version>',
...
```

docker-compose.yml
```
version: '3.4'
services:
    <name>:
        image: '<name>:<version>'
...
```

**Comment by dapplion** [comment]
Thanks for noticing this @sponnet. Do you believe that the manifest should overwrite the docker-compose.yml to make sure they match or throw an error and let the user fix inconsistencies?

**Comment by dapplion** [comment]
In the current release, the docker-compose is generated from the manifest each time.
