### ISSUE TITLE
`dappnodesdk build` ipfs step fails on normal wifi, works on dappnodewifi

### ISSUE THREAD

**Issue by wildmolasses** [dappnode/DAppNodeSDK#14]
On laptop running ipfs daemon...

Connected to my normal wifi:
```
Uploading docker image file .//build_0.0.1/dappnodepackage_trueblocks.public.dappnode.eth_0.0.1.tar.xz to IPFS...
Error: connect ETIMEDOUT 92.242.140.21:5001
```

Connected to dappnode wifi:
```
Uploading docker image file .//build_0.0.1/dappnodepackage_trueblocks.public.dappnode.eth_0.0.1.tar.xz to IPFS...
Uploading... 14.85%
Uploading... 29.70%
Uploading... 44.55%
Uploading... 59.40%
Uploading... 74.25%
Uploading... 89.09%
Uploading... 100.00%
```

May be a home networking issue, thought I'd log here anyway

**Comment by dapplion** [comment]
The dappnodesdk uses DAppNode's IPFS node by default unless you provided a specific (not documented) ENV. That is why it does not work on normal wifi. On the next version there will be an option `--provider` to specify a different IPFS node, such as infura or a localhost. Please watch progress on https://github.com/dappnode/DAppNodeSDK/tree/refactor
