### ISSUE TITLE
Close old dappnodebot/bump-upstream/* PRs

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNodeSDK#160]
In the bump-upstream ga, after successfully opening a new PR, look for older branches with prefix `dappnodebot/bump-upstream/`, and delete those branches + close associated PRs with a comment that references the new PR:
```
Closing for newer version https://github.com/dappnode/DAppNodePackage-turbo-geth/pull/9
```

**Comment by tropicar** [comment]
Done, there are only some packages with a PR with the prefix `dappnodebot/bump-upstream/` that require to be updated, but the old PR and branches were deleted and commented with a link to the newest PR.  The only packages with this old PR are archived and they are in mode read-only, so they cannot be deleted.

**Comment by dapplion** [comment]
@tropicar This issue was not about doing the work manually, but adding code in the DAppNodeSDK so it is done automatically by the bot
