### ISSUE TITLE
github action does not update the package version

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNodeSDK#164]
**Describe the bug**

The bump detects there is a new version on the official repository, and create PR and update the upstream version correctly, but the version of the dappnode package seems is not automatically updated.

**To Reproduce**

<!--Steps to reproduce the behavior:
These happened on the last prysm and pyrmont packages.

**Expected behavior**
The logic flow is when a new version is detected, and the PR with this new version is created the version changes too, increasing the last value.

**Comment by dapplion** [comment]
@tropicar  Can you link to a specific repo and GA run that you saw this error?

**Comment by tropicar** [comment]
For example, this happened on the last update of Prysm and pyrmont. This is the bump:
https://github.com/dappnode/DAppNodePackage-prysm-pyrmont/pull/44
The upstream versions changes, but the version of the package is no (this is the tab changes of the  PR bump):
```  "version": "0.1.16",
  "upstreamVersion": "v1.3.8",
  "upstreamVersion": "v1.3.9",```
  
  The GA of the repo seem correct, it would have to check the bump-stream action and why it fails on this package. 
  https://github.com/dappnode/DAppNodePackage-prysm-pyrmont/actions/runs/841531147/workflow

**Comment by dapplion** [comment]
@tropicar  Can you work on fixing this in the SDK side?

**Comment by tropicar** [comment]
Yes, of course

**Comment by pablomendezroyo** [comment]
did not happened anymore
