### ISSUE TITLE
bump-action only config github if this does not exist

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNodeSDK#168]
**Describe the bug**
If you execute the bump-action from a repository where there is a GitHub config, this configuration will be overridden with the "bot configuration".

**To Reproduce**

 you will see this configuration will be overridden.

**Expected behaviour**

Before setting up email,user. for GitHub, firstly, check if there is a GitHub user configuration on the directory.

**Comment by pablomendezroyo** [comment]
wont implement
