### ISSUE TITLE
Bump upstream should update version in manifest

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodeSDK#175]
The workflow used in most dappnode packages commonly named `auto-check.yml` is updating the upstream version. Would be a nice to have if it updates the version of the dappnode package in the manifest as well. An example:

![image](https://user-images.githubusercontent.com/41727368/125923084-6adae22b-9d16-4cb1-a9cc-9ffc788509df.png)

There should be updated the version from `0.3.5` to `0.3.6`

**Comment by dapplion** [comment]
That's a critical bug! It must update that field, please take a look when possible :pray:

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DAppNodeSDK/pull/320
