### ISSUE TITLE
![Uploading D4C60A99-2598-4E7D-9EA0-D905A1C562E4.png…]()

### ISSUE THREAD

**Issue by FAVE01** [dappnode/DAppNodeSDK#185]
![Uploading D4C60A99-2598-4E7D-9EA0-D905A1C562E4.png…]()

_Originally posted by @FAvE01 in https://github.com/dappnode/DAppNodeSDK/issues/182#issuecomment-968246966_

**Comment by dapplion** [comment]
Could you re-upload this image?

**Comment by pablomendezroyo** [comment]
not readable
