### ISSUE TITLE
Build dir has extra slash

### ISSUE THREAD

**Issue by wildmolasses** [dappnode/DAppNodeSDK#19]
Example console output:

> Saving docker image dappnodepackage_trueblocks.public.dappnode.eth:0.0.1 to file .//build_0.0.1/dappnodepackage_trueblocks.public.dappnode.eth_0.0.1.tar.xz...

This comes from dappnodesdk.js:

```js
 const buildDir = `${dir}/build_${nextVersion}/`;
```

`${dir}` default has a trailing slash: `./`

Is it ok to switch the definition of build dir to:

```js
 const buildDir = `${dir}build_${nextVersion}/`;
```

If so I can make a PR.

**Comment by dapplion** [comment]
Thank you @wildmolasses for noticing this! In the next version, I'm using Node's native module `path.join` which will solve this type of issues. Watch https://github.com/dappnode/DAppNodeSDK/tree/refactor for progress
