### ISSUE TITLE
Add property `exposeByDefault: boolean` to manifest exposable key

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodeSDK#191]
Allow developers to expose HTTPS ports by default on package installation.

``` 
exposable: [{
    "name": "Geth JSON RPC",
    "description": "JSON RPC endpoint for Geth mainnet",
    "serviceName": "beacon_chain",
    "port":  8545,
    "exposedByDefault": true
},
{
...
}
]
``` 

Set default `exposedByDefault`  value to `false`

Exposable manifest key: https://docs.dappnode.io/es/developers/manifest-reference/#exposable

**Comment by alexpeterson91** [comment]
Isn't the type an object array []? @pablomendezroyo

**Comment by pablomendezroyo** [comment]
> Isn't the type an object array []? @pablomendezroyo

right!
