### ISSUE TITLE
Do not allow to define compose values that are reserved for dappnode defaults

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodeSDK#235]
The dappmanager is adding a few `docker-compose.yml` values during installation as dappnode defaults, such as `dns` and `logging`. See https://github.com/dappnode/DNP_DAPPMANAGER/blob/f45e4bf89fe7c73c1d6d9784f5bc0af4dbf03075/packages/dappmanager/src/modules/compose/unsafeCompose.ts#L83

These values must be added during installation to have the power to change them with a core release. However, the SDK should not allow to define these compose values that are reserved for dappnode defaults. Instead, it should throw an error telling why to the developer.

Consider to define the "dappnode defaults" values here in the SDK and to be used as a dependency in the dappmanager for consistency

Dappnode values defaults
- `dns`
- `logging`
- `container_name`
- network aliases: `${dnpname}.dappnode`

Other possible values dappnode (defaults to discuss)
- compose `networks`?
- ?

**Comment by dapplion** [comment]
Yeah this is much better! It makes more sense

**Comment by pablomendezroyo** [comment]
already implemented
