### ISSUE TITLE
setup-wizard field service should allow to define more than 1 service at a time

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodeSDK#238]
**Describe the new setup-wizard feature you'd like**

The field `service` should be `string` or `string[]` to allow defining an env for multiple service. An example of necessity is the configuration of the fee recipient address, that is recommended to be configured on both: validator and beacon-chain services

**Describe alternatives you've considered**

NA

**Additional context**

https://docs.dappnode.io/developers/wizard/#service

**Comment by dapplion** [comment]
Sounds good
