### ISSUE TITLE
Parametrizable build timeout

### ISSUE THREAD

**Issue by adriamb** [dappnode/DAppNodeSDK#27]
In

https://github.com/dappnode/DAppNodeSDK/blob/master/src/methods/buildAndUpload.js#L12

there's a fixed 20m timeout for building the docker, but this is not enough for some builds that takes some time (like https://github.com/adriamb/tesseracts/tree/master/dappnode)

It would be nice if the build timeout is parametrizable.

**Comment by adriamb** [comment]
Duplicated of #25

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DAppNodeSDK/pull/28

**Comment by adriamb** [comment]
🎉
