### ISSUE TITLE
dAppNode README needs instructions to add to PATH

### ISSUE THREAD

**Issue by tjayrush** [dappnode/DAppNodeSDK#29]
I followed the instructions for installing dAppNodeSDK from the README.md file. After 

```
npm install -g @dappnode/dappnodesdk
```
I did the next command:

```
dappnodesdk init
```

and got this result

```
bash: dappnodesdk: command not found
```

Adding 

```
~/.npm-packages/bin/
```

to the PATH fixed the problem.

**Comment by dapplion** [comment]
Thanks for reporting! Fixed with https://github.com/dappnode/DAppNodeSDK/commit/79c1b177056bfc0acfce5a8575bf18542eccc5fa
