### ISSUE TITLE
Add attestations check for end to end tests in stakers

### ISSUE THREAD

**Issue by dsimog01** [dappnode/DAppNodeSDK#306]
In the end-to-end tests action, we can add the `probe of attestation` as one of the metrics for testing a new client or signer. In order to do this, we could have gnosis or prater validators with their keystores imported to the signer in the setup. We could also ensure that they are properly imported using the brain API.

On how to know if the validator has published attestations we can use the following endpoints of the beacon chain service:

`/eth/v1/beacon/validators/{validator_id}/attestations` -> Gets the attestations list for a specific validator
`/eth/v1/beacon/attestations?epoch={epoch}` -> Gets attestations for a specific epoch
`/eth/v1/beacon/attestations` -> Gets a list of attestations made by the node

**Comment by pablomendezroyo** [comment]
implemented
