### ISSUE TITLE
5

### ISSUE THREAD

**Issue by Lhokhilloo** [dappnode/DAppNodeSDK#432]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by alexpeterson91** [comment]
Yiu are a scammer and spammer I'm reporting you to GH I checked your activity and everything is just spam and what's not is scams adding demo workflows adding non GitHub workflows to customer addresses. You're a troll and scammer. Get out of this organization.
