### ISSUE TITLE
Ensure compose version is correct before building

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DAppNodeSDK#44]
<img width="867" alt="Screenshot 2019-09-19 at 16 12 36" src="https://user-images.githubusercontent.com/20141918/65253137-6b657080-dafa-11e9-9b1e-00ac84f9c219.png">

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DAppNodeSDK/commit/8b398ce7f015be661faec7fee62829613ae227eb
