### ISSUE TITLE
Compress image fails because of return value null !== 0

### ISSUE THREAD

**Issue by luxigo** [dappnode/DAppNodeSDK#51]
When I run "dappnodesdk build" the image compression fails because execa returns "null" instead of "0" as expected

at ChildProcess.<anonymous> (~/.nvm/versions/node/v12.12.0/lib/node_modules/@dappnode/dappnodesdk/src/utils/commands/compressFile.js:36:19)

https://github.com/dappnode/DAppNodeSDK/blob/7237c1e5b561f5dad663ac194f7ed4c963b5f8d5/src/utils/commands/compressFile.js#L34

the command was: 
```
xz -e9T0 -vv -f build_0.0.1/myapp.public.dappnode.eth_0.0.1.tar & xz_pid=$!
while sleep 1; do
  kill -ALRM "$xz_pid" || break
done
wait "$xz_pid"
```
xz --version returns:
```
xz (XZ Utils) 5.2.2
liblzma 5.2.2
```
A more relaxed comparison (!code) instead of (code===0) would fix the issue, but better fix execa so that 0 is returned instead of null IMO.

**Comment by dapplion** [comment]
@luxigo Thanks for reporting, will fix it asap. What OS did you run the dappnodesdk on?
